extend type User {
  watchlist: [String]
}

type Watch {
  id: Int,
  symbol: String,
  sys_create_time: DateTime
  sys_update_time: DateTime
  sys_delete_time: DateTime
}

extend type Query {
  get_watch(
    id: Int!
  ): [Watch]
}

extend type Mutation {
  add_watch(
    id: Int!
    symbol: String!
  ): String
}
