extend type Query {
  watchlist(
    id: Int!
  ): [Watch]
}

extend type Mutation {
  add_watch(
    id: Int!
    symbol: String!
  ): Watch
}

type Watch {
  id: Int
  symbol: String
  sys_create_time: DateTime
  sys_update_time: DateTime
  sys_delete_time: DateTime
}
