extend type Query {
  user(
    email: String!
    password: String!
  ): User
}

extend type Mutation {
  signup(
    email: String!
    name: String!
    password: String!
  ): User
}

type User {
  jwt: String
  id: Int
  name: String
  email: String
  password: String
  avatar: String
  sys_create_time: DateTime
  sys_update_time: DateTime
  sys_delete_time: DateTime
}