extend type Security {
  stock_price: StockPrice
}

type StockPrice {
  intraday: Price
  daily: Price
}

type Price {
  last_refreshed: String
  time_zone: String
  prices: [TradePrice]
}

type TradePrice {
  open: String
  high: String
  low: String
  close: String
  volume: String
  datetime:String
}